# Initial version generated with
# { echo "-R . FinProof " ; find . -name "*.v" -print } > _CoqProject

-R ./src flexProject
-R ../ursus/pruvendo-ursus-tvm/_build/default/src UrsusTVM
-R ../ursus/coq-finproof-base/_build/default/src FinProof
-R ../ursus/pruvendo-base-lib/_build/default/src FinProof.Lib
-R ../ursus/solidity-monadic-language/_build/default/src UMLang
-R ../ursus/ursus-standard-library/_build/default/src UrsusStdLib


./src/Contracts/TONTokenWallet/Ledger.v
./src/Contracts/TONTokenWallet/Functions/FuncSig.v
./src/Contracts/TONTokenWallet/Functions/Funcs.v
./src/Contracts/TONTokenWallet/Functions/FuncNotations.v
./src/Contracts/TONTokenWallet/Interface.v
./src/Contracts/TONTokenWallet/ClassTypes.v
./src/Contracts/TONTokenWallet/ClassTypesNotations.v
./src/Contracts/FlexClient/Ledger.v
./src/Contracts/FlexClient/CommonProofs/StateProofs.v
./src/Contracts/FlexClient/Functions/_unused/Funcs.v
./src/Contracts/FlexClient/Functions/_unused/FuncNotations.v
./src/Contracts/FlexClient/Functions/FuncSig.v
./src/Contracts/FlexClient/Functions/Funcs.v
./src/Contracts/FlexClient/Functions/FuncNotations.v
./src/Contracts/FlexClient/Interface.v
./src/Contracts/FlexClient/ClassTypes.v
./src/Contracts/FlexClient/Features/Spec/SpecSig.v
./src/Contracts/FlexClient/Features/Proofs/Feature1.v
./src/Contracts/FlexClient/Features/Proofs/Feature2.v
./src/Contracts/FlexClient/_EvalExecs/_Proofs/constructor.v
./src/Contracts/FlexClient/_EvalExecs/_Proofs/deploy.v
./src/Contracts/FlexClient/_EvalExecs/Spec/SpecSig.v
./src/Contracts/FlexClient/_EvalExecs/Templates.v
./src/Contracts/FlexClient/ClassTypesNotations.v
./src/Contracts/RootTokenContract/Ledger.v
./src/Contracts/RootTokenContract/Functions/FuncSig.v
./src/Contracts/RootTokenContract/Functions/Funcs.v
./src/Contracts/RootTokenContract/Functions/FuncNotations.v
./src/Contracts/RootTokenContract/Interface.v
./src/Contracts/RootTokenContract/ClassTypes.v
./src/Contracts/RootTokenContract/ClassTypesNotations.v
./src/Contracts/Wrapper/Ledger.v
./src/Contracts/Wrapper/CommonProofs/StateProofs.v
./src/Contracts/Wrapper/Functions/FuncSig.v
./src/Contracts/Wrapper/Functions/Funcs.v
./src/Contracts/Wrapper/Functions/FuncNotations.v
./src/Contracts/Wrapper/Interface.v
./src/Contracts/Wrapper/ClassTypes.v
./src/Contracts/Wrapper/ClassTypesNotations.v
./src/Contracts/PriceXchg/Ledger.v
./src/Contracts/PriceXchg/CommonProofs/StateProofs.v
./src/Contracts/PriceXchg/_EvalExec/Spec/SpecSig.v
./src/Contracts/PriceXchg/_EvalExec/Proofs/constructor.v
./src/Contracts/PriceXchg/_EvalExec/Proofs/deploy.v
./src/Contracts/PriceXchg/_EvalExec/Templates.v
./src/Contracts/PriceXchg/Functions/FuncSig.v
./src/Contracts/PriceXchg/Functions/Funcs.v
./src/Contracts/PriceXchg/Functions/FuncNotations.v
./src/Contracts/PriceXchg/Interface.v
./src/Contracts/PriceXchg/ClassTypes.v
./src/Contracts/PriceXchg/Features/Spec/SpecSig.v
./src/Contracts/PriceXchg/Features/Proofs/Feature1.v
./src/Contracts/PriceXchg/Features/Proofs/Feature2.v
./src/Contracts/PriceXchg/ClassTypesNotations.v
./src/Contracts/Flex/Ledger.v
./src/Contracts/Flex/CommonProofs/StateProofs.v
./src/Contracts/Flex/Functions/_unused/Funcs.v
./src/Contracts/Flex/Functions/FuncSig.v
./src/Contracts/Flex/Functions/Funcs.v
./src/Contracts/Flex/Functions/FuncNotations.v
./src/Contracts/Flex/Interface.v
./src/Contracts/Flex/ClassTypes.v
./src/Contracts/Flex/Features/Spec/SpecSig.v
./src/Contracts/Flex/Features/Proofs/Feature1.v
./src/Contracts/Flex/Features/Proofs/Feature2.v
./src/Contracts/Flex/_EvalExecs/_Proofs/constructor.v
./src/Contracts/Flex/_EvalExecs/_Proofs/deploy.v
./src/Contracts/Flex/_EvalExecs/Spec/SpecSig.v
./src/Contracts/Flex/_EvalExecs/Templates.v
./src/Contracts/Flex/ClassTypesNotations.v
./src/Contracts/XchgPair/Ledger.v
./src/Contracts/XchgPair/CommonProofs/StateProofs.v
./src/Contracts/XchgPair/_EvalExec/Spec/SpecSig.v
./src/Contracts/XchgPair/_EvalExec/Proofs/constructor.v
./src/Contracts/XchgPair/_EvalExec/Proofs/deploy.v
./src/Contracts/XchgPair/_EvalExec/Templates.v
./src/Contracts/XchgPair/Functions/FuncSig.v
./src/Contracts/XchgPair/Functions/Funcs.v
./src/Contracts/XchgPair/Functions/FuncNotations.v
./src/Contracts/XchgPair/Interface.v
./src/Contracts/XchgPair/ClassTypes.v
./src/Contracts/XchgPair/Features/Spec/SpecSig.v
./src/Contracts/XchgPair/Features/Proofs/Feature1.v
./src/Contracts/XchgPair/Features/Proofs/Feature2.v
./src/Contracts/XchgPair/ClassTypesNotations.v
./src/Contracts/Price/Ledger.v
./src/Contracts/Price/CommonProofs/StateProofs.v
./src/Contracts/Price/Functions/FuncSig.v
./src/Contracts/Price/Functions/Funcs.v
./src/Contracts/Price/Functions/FuncNotations.v
./src/Contracts/Price/Interface.v
./src/Contracts/Price/ClassTypes.v
./src/Contracts/Price/Features/Spec/SpecSig.v
./src/Contracts/Price/Features/Proofs/Feature1.v
./src/Contracts/Price/Features/Proofs/Feature2.v
./src/Contracts/Price/_EvalExecs/Spec/SpecSig.v
./src/Contracts/Price/_EvalExecs/Proofs/constructor.v
./src/Contracts/Price/_EvalExecs/Proofs/deploy.v
./src/Contracts/Price/_EvalExecs/Templates.v
./src/Contracts/Price/ClassTypesNotations.v
./src/Contracts/TradingPair/Ledger.v
./src/Contracts/TradingPair/CommonProofs/StateProofs.v
./src/Contracts/TradingPair/Functions/_unused/Funcs.v
./src/Contracts/TradingPair/Functions/FuncSig.v
./src/Contracts/TradingPair/Functions/Funcs.v
./src/Contracts/TradingPair/Functions/FuncNotations.v
./src/Contracts/TradingPair/Interface.v
./src/Contracts/TradingPair/ClassTypes.v
./src/Contracts/TradingPair/Features/Spec/SpecSig.v
./src/Contracts/TradingPair/Features/Proofs/Feature1.v
./src/Contracts/TradingPair/Features/Proofs/Feature2.v
./src/Contracts/TradingPair/_EvalExecs/_Proofs/constructor.v
./src/Contracts/TradingPair/_EvalExecs/_Proofs/deploy.v
./src/Contracts/TradingPair/_EvalExecs/Spec/SpecSig.v
./src/Contracts/TradingPair/_EvalExecs/Templates.v
./src/Contracts/TradingPair/ClassTypesNotations.v
./src/Project/CommonAxioms.v
./src/Project/CommonConsts.v
./src/Project/CommonConstSig.v
./src/Project/CommonNotations.v
./src/Project/CommonTypesProofs.v
./src/Project/CommonTypes.v
./_unused/CommonTypesNotations.v
